### ISSUE TITLE
Hello Majur Divate, I am trying to analyze my ATACseq data. I could successfully run build the genome index, but when I try to start the Data Analysis program it tells me Macs 2 version is not found, even though I have installed. When I run the configuration it tells me that macs is already installed. What can I do. Thanks

### ISSUE THREAD

**Issue by santicerri** [MayurDivate/GUAVASourceCode#10]

**Comment by santicerri** [comment]
when I run the configuration this appears: 
>>> >> > Installing dependencies > >> >>>
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
>>>>> FOUND: java <<<<<
>>>>> FOUND: bedtools <<<<<
>>>>> FOUND: bowtie <<<<<
>>>>> FOUND: bowtie2 <<<<<
>>>>> FOUND: cutadapt <<<<<
>>>>> FOUND: fastqc <<<<<
>>>>> FOUND: samtools <<<<<
>>>>> FOUND: picard <<<<<
>>>>> FOUND: igv <<<<<
>>>>> FOUND: bedGraphToBigWig <<<<<



>>> MACS2 is already installed ! 
>>>>>>>>> Finished <<<<<<<<<

But when I load the program it appears this:
Operating System of machine :Mac OS X
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		MACS2 version (macs2 2.1.1.20160309) :			NOT FOUND !!!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!

There are missing dependancies!
Please use configure.sh to install dependencies.

**Comment by MayurDivate** [comment]
Please use the command below to install correct MACS2 version.
pip install MACS2==2.1.1.20160309
(use sudo if required)

Cheers,
Mayur
