### ISSUE TITLE
Problem with creation of index

### ISSUE THREAD

**Issue by Laurent2873** [MayurDivate/GUAVASourceCode#12]
Hi

Thanks for creating Guava. Might turn very useful although the pipeline is constantly updating and macs2 might not be used anymore. Before I even get there I have problem creating the index.
Everything seems to be installed correctly yet when I start the creation of the index I get this error 

GUAVA version 1
Apr 10, 2019 5:19:39 PM umac.guava.genomeindexbuilder.GenomeIndexBuilder runCommand
SEVERE: null
java.io.IOException: Cannot run program "bowtie2-build": error=2, No such file or directory

I know that bowtie2 is installed
>>> >> > Installing dependencies > >> >>>
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
>>>>> FOUND: java <<<<<
>>>>> FOUND: bedtools <<<<<
>>>>> FOUND: bowtie <<<<<
>>>>> FOUND: bowtie2 <<<<<
>>>>> FOUND: cutadapt <<<<<
>>>>> FOUND: fastqc <<<<<
>>>>> FOUND: samtools <<<<<
>>>>> FOUND: picard <<<<<
>>>>> FOUND: igv <<<<<
>>>>> FOUND: bedGraphToBigWig <<<<<

Any idea?

Thanks
PS: wondering whether in the future you can include multiple sample comparison, k-mean clustering of differentially accessible peaks etc... ;)

**Comment by MayurDivate** [comment]
Hi @Laurent2873 ,

try running following command on the terminal and let me know the output. 
> bowtie2-build --version 
> which bowtie2-build

thanks
Mayur

**Comment by Laurent2873** [comment]
Hi Mayur,

Installing the new version of Macs2 with
sudo pip install MACS2==2.1.1.20160309
fixed the problem and now it seemed to have everything in place.
This is quite resource intensive for my machine and I ran one analysis overnight.
It didn’t go through with an error code 101

Laurent
