### ISSUE TITLE
Fastq files are split up

### ISSUE THREAD

**Issue by woeulii** [MayurDivate/GUAVASourceCode#13]
Hi,
I am trying to use GUAVA and realized that my sequencing files have been split up in several fastq files. Is there a way to align the reads using GUAVA if there are several fastq files for one sample?

Thanks in advance!

**Comment by MayurDivate** [comment]
At the moment there is no way to feed multiple R1 and R2 fastq files.
But you can concatenate those together using 'cat command'. 
Then use it for processing.

Cheers,
Mayur
