### ISSUE TITLE
Error in the differential analysis step, analysis stopped

### ISSUE THREAD

**Issue by eryildiz** [MayurDivate/GUAVASourceCode#24]
Thanks for the tool!

[MV411_par_vs_ko1_log.txt](https://github.com/MayurDivate/GUAVASourceCode/files/4100010/MV411_par_vs_ko1_log.txt)
Please see the log file for the error.

I have used the R script that it generated though and by changing this
`vsd <- vst(dds, blind=FALSE)`
to this
`vsd <- varianceStabilizingTransformation(dds)`

I could complete the analysis. Is there a way to modify this?

**Comment by MayurDivate** [comment]
you can download source code and modify line number 171 in the following [file](https://github.com/MayurDivate/GUAVASourceCode/blob/master/src/umac/guava/diff/DESeq2.java).
