### ISSUE TITLE
Bowtie not found when running ATAC-seq analysis

### ISSUE THREAD

**Issue by ruifengy** [MayurDivate/GUAVASourceCode#25]
Dear @MayurDivate 
I get an error while trying to run Guava fro ATAC-seq analysis:
Operating System of machine :Linux
		cutadapt:		Working!
		bowtie:			NOT FOUND !!!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		macs2:		Working!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!

There are missing dependancies!
Please use configure.sh to install dependencies.

But actually I install the bowtie:
bowtie --version
/home/ruifeng/miniconda2/bin/bowtie-align-s version 1.2.3
64-bit
Built on default-48fbded5-06a5-4dc9-a834-ed5218bd4764
Tue Sep 17 15:33:07 UTC 2019
Compiler: gcc version 7.3.0 (crosstool-NG 1.23.0.449-a04d0) 
Options: -O3 -m64 -I/home/ruifeng/miniconda2/include -L/home/ruifeng/miniconda2/lib -Wl,--hash-style=both -DWITH_TBB -DPOPCNT_CAPABILITY -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/ruifeng/miniconda2/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie_1568734259982/work=/usr/local/src/conda/bowtie-1.2.3 -fdebug-prefix-map=/home/ruifeng/miniconda2=/usr/local/src/conda-prefix  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/ruifeng/miniconda2/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie_1568734259982/work=/usr/local/src/conda/bowtie-1.2.3 -fdebug-prefix-map=/home/ruifeng/miniconda2=/usr/local/src/conda-prefix 
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
Is there a way to fix this?
Thanks

**Comment by MayurDivate** [comment]
you will have to add bowtie to the system path.

append the bowtie path to PATH variable : (https://askubuntu.com/questions/109381/how-to-add-path-of-a-program-to-path-environment-variable)
