### ISSUE TITLE
GUAVA Manual

### ISSUE THREAD

**Issue by MargheritaSq** [MayurDivate/GUAVASourceCode#27]
Hi!

I would like to use GUAVA to analyze ATAC-Seq data that some colleagues of mine will provide me. Before this step I would like to make some practice with this tool analyzing some available dataset from GEO database but I can't find the manual. Where I can find it? Thank you very much in advance.

**Comment by MayurDivate** [comment]
[Manual](https://github.com/MayurDivate/GUAVASourceCode/blob/master/GUAVA_manual.pdf)
