### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by MargheritaSq** [MayurDivate/GUAVASourceCode#29]
Hi!

It's me again. I cannot download the Sample dataset. The link does not work. Can u help me?
I have tried to download from the manual and from here but this address seems broken : http://ec2-52-201-246-161.compute-1.amazonaws.com/guava/

Thank you.

**Comment by MargheritaSq** [comment]
The message is "This site can’t be reached". Thanks

**Comment by MayurDivate** [comment]
I try to upload it somewhere else.

**Comment by MargheritaSq** [comment]
Thank u very much! I will wait for it.
