### ISSUE TITLE
Bowtie2 indexes

### ISSUE THREAD

**Issue by AndyPuig** [MayurDivate/GUAVASourceCode#6]
Hello Mayur

Thank you so much for the GUAVA project! 
I have a question regarding the bowtie2 indexes for the alignment.  After using the GUAVA genome index builder tool I ended up with six .bt2 files. Should I use all of them for the analysis? And if so, how can I do it on GUAVA?

Thank you ! 
Andrés

**Comment by MayurDivate** [comment]
Hi Andrés,

No, just select any one of those files and GUAVA will take care of the rest.

Cheers,
Mayur

**Comment by AndyPuig** [comment]
Thank you! 

Andrés
