### ISSUE TITLE
Error code 101: Unexpected exit from analysis workflow

### ISSUE THREAD

**Issue by fdmac** [MayurDivate/GUAVASourceCode#9]
Hello,

I recently installed GUAVA and was trying to analyze the sample data set, but I keep getting the following error:

Adapter trimming...Done
fastq QC...
Alignment...
Please wait while bowtie2 alignment is finished..Done!
Error code 101: Unexpected exit from analysis workflow

Any insight you might be able to provide would be greatly appreciated. Would I have to uninstall and reinstall?

Thanks in advance!

**Comment by fdmac** [comment]
It appears that allocating more system resources did the trick -- sorry for the premature question!

**Comment by smbchu** [comment]
Hi! what does allocating more system means?

**Comment by smbchu** [comment]
> Hi! what does allocating more system means?

how can I also do it? Please help. I'm very new to this.

**Comment by MayurDivate** [comment]
Try using more CPUs and RAM.

Mayur

**Comment by DavidZepecki** [comment]
Hi fdmac and everyone else, I encountered this very same problem. However allocating more heap memory using the Xmx command did not do the trick for me. fdmac can you please clarify how precisely you "allocated more systems resources"? I am working on a bit of a deadline and would appreciate any type of clarification. Thanks guys!
